### ISSUE TITLE
\ should work with zero matrices

### ISSUE THREAD

**Issue by cossio** [JuliaLang/LinearAlgebra.jl#6] opened 2022-11-26 22:30 UTC
```
julia> A = zeros(2,2); B = randn(2,2);

julia> A \ B
ERROR: SingularException(1)
Stacktrace:
 [1] ldiv!(B::Matrix{Float64}, D::Diagonal{Float64, Vector{Float64}}, A::Matrix{Float64})
   @ LinearAlgebra ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:435
 [2] \(D::Diagonal{Float64, Vector{Float64}}, B::Matrix{Float64})
   @ LinearAlgebra ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/diagonal.jl:422
 [3] \(A::Matrix{Float64}, B::Matrix{Float64})
   @ LinearAlgebra ~/.julia/juliaup/julia-1.8.3+0.x64/share/julia/stdlib/v1.8/LinearAlgebra/src/generic.jl:1102
 [4] top-level scope
   @ REPL[7]:1
```

This should work, and be equivalent to `pinv(A) * B`:

```
julia> pinv(A) * B
2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
```

**Comment by DrTimothyAldenDavis** [comment] 2022-11-27 00:07
I think this would be a costly sledge-hammer to merge the pseudo-inverse into the backslash operator.  The difficulty would be knowing when A\b (using LU, QR, or Cholesky factorization) fails badly enough to warrant the use of the SVD with pinv(A).  If A is ill-conditioned, A\b will still work but might be somewhat inaccurate.  Or exceedingly inaccurate.  In the latter case you might want to punt to pinv(A)*b, but how to decide that automatically?  pinv(A)*b can take 1000x, a million times, or a billion times more work than A\b.  It can be arbitrarily costly, since A\b can take as little as O(n) work but pinv(A)*b is always O(n^3) and with a much much larger constant than, say, matrix-matrix multiply.

Even if A is perfectly singular, not just nearly singular, Julia would seem to freeze if it tried pinv(A)*b when detecting this condition, because the run time of pinv(A)*b can be so exceedingly high.

It would be better to catch this error in the user-code ("if A\b fails then do pinv(A)*b") so it's only done on an opt-in basis.

**Comment by stevengj** [comment] 2022-11-27 01:38
Duplicate of #46164.

**Closed by stevengj** 2022-11-27 01:38 UTC
